// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IssuesManagement
{
    [Table("Issue")]
    public partial class Issue
    {
        [Key]
        public int IssueId { get; set; }
        [Required]
        [StringLength(50)]
        public string Title { get; set; }
        [StringLength(2000)]
        public string Description { get; set; }
        public bool StatusOpened { get; set; }
        public int? AssignedTo { get; set; }

        [ForeignKey(nameof(AssignedTo))]
        public virtual User AssignedToNavigation { get; set; }
    }
}