// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Tickets
{
    [Table("Status")]
    public partial class Status
    {
        [Key]
        [StringLength(1)]
        public string StatusCode { get; set; }
        [StringLength(20)]
        public string StatusDesc { get; set; }
    }
}