// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Tickets
{
    public partial class Ticket
    {
        [Key]
        public int TicketId { get; set; }
        [Required]
        [StringLength(50)]
        public string Title { get; set; }
        [StringLength(2000)]
        public string Description { get; set; }
        public int ProjectId { get; set; }
        [Required]
        [StringLength(1)]
        public string StatusCode { get; set; }
        public int? TimeSpend { get; set; }
        public int? TimeRemaining { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateCreated { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateUpdated { get; set; }
        public int? EmployeeId { get; set; }

        [ForeignKey(nameof(EmployeeId))]
        public virtual Employee Employee { get; set; }

        [ForeignKey(nameof(ProjectId))]
        public virtual Project Project { get; set; }
        
        [ForeignKey(nameof(StatusCode))]
        public virtual Status Status { get; set; }
    }
}