/* tslint:disable */
/* eslint-disable */
/**
 * IssuesManagement.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Issue
 */
export interface Issue {
    /**
     * 
     * @type {number}
     * @memberof Issue
     */
    issueId?: number;
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    description?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof Issue
     */
    statusOpened?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    readonly status?: string | null;
}

export function IssueFromJSON(json: any): Issue {
    return IssueFromJSONTyped(json, false);
}

export function IssueFromJSONTyped(json: any, ignoreDiscriminator: boolean): Issue {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'issueId': !exists(json, 'issueId') ? undefined : json['issueId'],
        'title': json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'statusOpened': !exists(json, 'statusOpened') ? undefined : json['statusOpened'],
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function IssueToJSON(value?: Issue | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'issueId': value.issueId,
        'title': value.title,
        'description': value.description,
        'statusOpened': value.statusOpened,
    };
}


