// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IssuesManagement.Services;
using IssuesManagement.Services.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace IssuesManagement.Services.Data.Configurations
{
    public partial class IssueConfiguration : IEntityTypeConfiguration<Issue>
    {
        public void Configure(EntityTypeBuilder<Issue> entity)
        {
            entity.ToTable("Issue");

            entity.Property(e => e.Description)
                .HasMaxLength(2000)
                .IsUnicode(false);

            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.AssignedToNavigation)
                .WithMany()
                .HasForeignKey(d => d.AssignedTo)
                .HasConstraintName("FK_Issue_User");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Issue> entity);
    }
}
