// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using Tickets.Services;
using Tickets.Services.Data;

namespace Tickets.Services.Data.Configurations
{
    public partial class StatusConfiguration : IEntityTypeConfiguration<Status>
    {
        public void Configure(EntityTypeBuilder<Status> entity)
        {
            entity.HasKey(e => e.StatusCode)
                .IsClustered(false);

            entity.Property(e => e.StatusCode)
                .HasMaxLength(1)
                .IsFixedLength();

            entity.Property(e => e.StatusDesc)
                .HasMaxLength(20)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Status> entity);
    }
}
