// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Tickets
{
    public partial class Project
    {
        public Project()
        {
            Tickets = new HashSet<Ticket>();
        }

        [Key]
        public int ProjectId { get; set; }
        [Required]
        [StringLength(50)]
        public string ProjectName { get; set; }
        [Required]
        [StringLength(1)]
        public string StatusCode { get; set; }
        [StringLength(2000)]
        public string Description { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateCreated { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateUpdated { get; set; }

        [ForeignKey(nameof(StatusCode))]
        public virtual Status StatusCodeNavigation { get; set; }

        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}