// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IssuesManagement.Services;
using IssuesManagement.Services.Data.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using System;
using System.Collections.Generic;
#nullable disable

namespace IssuesManagement.Services.Data
{
    public partial class IssuesDbContext : DbContext
    {
        public IssuesDbContext()
        {
        }

        public IssuesDbContext(DbContextOptions<IssuesDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Issue> Issues { get; set; }
        public virtual DbSet<User> Users { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new Configurations.IssueConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.UserConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
